sudo: required
services:
  - docker

before_install:
  - docker build -t sanchitb23/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -r CI=true sanchitb23/react-test npm test

after_success:
  - docker build -t sanchitb23/complex-client ./client
  - docker build -t sanchitb23/complex-nginx ./nginx
  - docker build -t sanchitb23/complex-server ./server
  - docker build -t sanchitb23/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sanchitb23/complex-client
  - docker push sanchitb23/complex-nginx
  - docker push sanchitb23/complex-server
  - docker push sanchitb23/complex-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: mutli-docker
  env: MultiDocker-env
  bucket: s3bucketname
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

